### ISSUE TITLE
Error if i make call audio or video and if i accept what sould i do ???

### ISSUE THREAD

**Issue by Moatamed8** [cloudwebrtc/dart-sip-ua#233]
E/flutter ( 1705): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Unable to getUserMedia: getUserMedia(): DOMException, NotAllowedError
E/flutter ( 1705): #0      MediaDeviceNative.getUserMedia (package:flutter_webrtc/src/native/mediadevices_impl.dart:29:7)
E/flutter ( 1705): <asynchronous suspension>
E/flutter ( 1705): #1      _MyCallScreenWidget._handleAccept (package:dart_sip_ua_example/src/callscreen.dart:229:21)
E/flutter ( 1705): <asynchronous suspension>
E/flutter ( 1705):

**Comment by duy1998** [comment]
<uses-feature android:name="android.hardware.camera" />
<uses-feature android:name="android.hardware.camera.autofocus" />
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.RECORD_AUDIO" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
 You should add that codes in Android Manifest
