### ISSUE TITLE
Android 10 and Fluter 1.12?

### ISSUE THREAD

**Issue by ghenry** [cloudwebrtc/dart-sip-ua#55]
**Describe the bug**
`flutter run` fails

```
~/src/dart-sip-ua/example [master*]$ flutter run
Running "flutter pub get" in example...                             0.5s
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> More than one file was found with OS independent path 'META-INF/proguard/androidx-annotations.pro'
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 21s                                                     
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        21.7s
AndroidX incompatibilities may have caused this build to fail. Please migrate your app to AndroidX. See https://goo.gl/CP92wY.
Gradle task assembleDebug failed with exit code 1


~/src/dart-sip-ua/example [master*]$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_GB.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.40.2)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by cloudwebrtc** [comment]
Hi, @ghenry  I don't have an AndroidX device, but I run it on the emulator. Adding the `--androidx` parameter to the `flutter create` command seems to work.

https://github.com/cloudwebrtc/dart-sip-ua/blob/master/example/scripts/project_tools.sh#L18

It looks like this:

```
flutter create --android-language java --androidx --ios-language objc --project-name $FLUTTER_APP_PROJECT_NAME --org $FLUTTER_APP_ORG .
```

If your test is valid, I can update the repository immediately.

**Comment by ghenry** [comment]
Thanks. I added that (using flutter stable - 1.12):

```
Create flutter project: name=surevoip_talk, org=com.surevoip.talk ...
Recreating project ....
  android/app/build.gradle (created)
  android/app/src/main/java/com/surevoip/talk/surevoip_talk/MainActivity.java (created)
  android/build.gradle (created)
  android/surevoip_talk_android.iml (created)
  test/widget_test.dart (created)
  surevoip_talk.iml (created)
  .metadata (created)
  android/app/src/debug/AndroidManifest.xml (created)
  android/app/src/profile/AndroidManifest.xml (created)
  android/app/src/main/AndroidManifest.xml (created)
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png (created)
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png (created)
  android/app/src/main/res/values/styles.xml (created)
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png (created)
  android/app/src/main/res/drawable/launch_background.xml (created)
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png (created)
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png (created)
  android/.gitignore (created)
  android/settings.gradle (created)
  android/gradle.properties (created)
  android/gradle/wrapper/gradle-wrapper.properties (created)
  ios/Runner/main.m (created)
  ios/Runner/AppDelegate.h (created)
  ios/Runner/AppDelegate.m (created)
  ios/Runner.xcodeproj/project.pbxproj (created)
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (created)
  ios/Runner/Info.plist (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png (created)
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png (created)
  ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md (created)
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png (created)
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png (created)
  ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json (created)
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png (created)
  ios/Runner/Base.lproj/LaunchScreen.storyboard (created)
  ios/Runner/Base.lproj/Main.storyboard (created)
  ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata (created)
  ios/.gitignore (created)
  ios/Runner.xcworkspace/contents.xcworkspacedata (created)
  ios/Flutter/AppFrameworkInfo.plist (created)
  ios/Flutter/Debug.xcconfig (created)
  ios/Flutter/Release.xcconfig (created)
  .idea/libraries/Flutter_for_Android.xml (created)
  .idea/libraries/KotlinJavaRuntime.xml (created)
  .idea/libraries/Dart_SDK.xml (created)
  .idea/workspace.xml (created)
  .idea/runConfigurations/main_dart.xml (created)
  .idea/modules.xml (created)
Running "flutter pub get" in example...                            31.4s
Wrote 65 files.

All done!
[✓] Flutter: is fully installed. (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_GB.UTF-8)
[✓] Android toolchain - develop for Android devices: is fully installed. (Android SDK version 28.0.3)
[✓] Android Studio: is fully installed. (version 3.5)
[✓] VS Code: is fully installed. (version 1.41.1)
[✓] Connected device: is fully installed. (1 available)

In order to run your application, type:

  $ cd .
  $ flutter run

Your application code is in ./lib/main.dart.


Add permission labels to Info.plist.

Insert 	<key>NSCameraUsageDescription</key> to line 25
Insert 	<string>$(PRODUCT_NAME) Camera Usage!</string> to line 26
Insert 	<key>NSMicrophoneUsageDescription</key> to line 27
Insert 	<string>$(PRODUCT_NAME) Microphone Usage!</string> to line 28
Traceback (most recent call last):
  File "add-line.py", line 71, in <module>
    main(sys.argv[1:])
  File "add-line.py", line 66, in main
    replaceText(inputfile, string, text)
  File "add-line.py", line 34, in replaceText
    with open(filename, 'r') as fp:
IOError: [Errno 2] No such file or directory: '../ios/Podfile'

Add permission labels to AndroidManifest.xml.

Replace minSdkVersion 16 to minSdkVersion 18
Insert     <uses-permission android:name="android.permission.CAMERA" /> to line 8
Insert     <uses-permission android:name="android.permission.RECORD_AUDIO" /> to line 9
Insert     <uses-permission android:name="android.permission.WAKE_LOCK" /> to line 10
Insert     <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" /> to line 11
Insert     <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" /> to line 12
Insert     <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" /> to line 13
Insert     <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" /> to line 14
```

**Comment by cloudwebrtc** [comment]
It should be impossible to create a complete`ios` project under `Linux`, so the `ios/Podfile` does not exist, and the script needs to add platform conditions.
